import os
from subprocess import Popen, PIPE
import sys

from source.input_output.read_msms import read_msms
from source.triangulation.xyzrn import output_pdb_as_xyzrn
from source.default_config.global_vars import msms_bin 
from source.default_config.masif_opts import masif_opts
import random

# Pablo Gainza LPDI EPFL 2017-2019
# Calls MSMS and returns the vertices.
# Special atoms are atoms with a reduced radius.
def computeMSMS(pdb_file,  protonate=True):
    randnum = random.randint(1,10000000)
    file_base = masif_opts['tmp_dir']+"/msms_"+str(randnum)
    out_xyzrn = file_base+".xyzrn"

    # If protonate is set to True, it calls the output_pdb_as_xyzrn function to convert the PDB file to XYZRN format, 
    # which includes information about atom coordinates, radii, and charges.
    if protonate:        
        output_pdb_as_xyzrn(pdb_file, out_xyzrn)
    else:
        print("Error - pdb2xyzrn is deprecated.")
        sys.exit(1)

    # Now run MSMS on xyzrn file: This section of code sets up the command-line arguments for running MSMS and calls it using Popen. 
    # It specifies various parameters such as density, probe radius, and input/output file paths. MSMS is executed as a subprocess, 
    # and the standard output and standard error are captured.
    FNULL = open(os.devnull, 'w')
    args = [msms_bin, "-density", "3.0", "-hdensity", "3.0", "-probe",\
                    "1.5", "-if",out_xyzrn,"-of",file_base, "-af", file_base]
    #print msms_bin+" "+`args`
    p2 = Popen(args, stdout=PIPE, stderr=PIPE)
    stdout, stderr = p2.communicate()

    # The script reads the output files generated by MSMS, including the surface vertices, faces, normals, and atom names. 
    # Additionally, it reads the surface area information from the .area file.  Temporary files created during the MSMS 
    # computation are then removed, and the function returns the computed vertices, faces, normals, atom names, and surface areas.
    vertices, faces, normals, names = read_msms(file_base)
    areas = {}
    ses_file = open(file_base+".area")
    next(ses_file) # ignore header line
    for line in ses_file:
        fields = line.split()
        areas[fields[3]] = fields[1]


    # Remove temporary files. 
    os.remove(file_base+'.area')
    os.remove(file_base+'.xyzrn')
    os.remove(file_base+'.vert')
    os.remove(file_base+'.face')
    return vertices, faces, normals, names, areas

